# Generated by Django 5.2.7 on 2025-10-13 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, default='yookassa', max_length=20)),
                ('payment_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(db_index=True, max_length=32)),
                ('event', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tickets.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
