# Generated by Django 5.2.7 on 2025-10-11 15:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название тарифа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Афиша')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('starts_at', models.DateTimeField(verbose_name='Дата и время начала')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность, мин')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликовано'), ('rejected', 'Отклонено')], default='draft', max_length=20, verbose_name='Статус')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Общая вместимость')),
                ('available_tickets', models.PositiveIntegerField(default=0, verbose_name='Остаток билетов (денорм.)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.category', verbose_name='Категория')),
                ('organizer', models.ForeignKey(limit_choices_to={'is_organizer': True}, on_delete=django.db.models.deletion.PROTECT, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EventTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('available_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Квота')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='Продано')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tariffs', to='events.event', verbose_name='Событие')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_tariffs', to='events.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Тариф события',
                'verbose_name_plural': 'Тарифы события',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='events_even_slug_30eb0f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'starts_at'], name='events_even_status_5c3d55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventtariff',
            unique_together={('event', 'tariff')},
        ),
    ]
