# Generated by Django 5.2.7 on 2025-10-13 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_moderated_by_event_moderation_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_description', models.TextField()),
                ('new_image', models.ImageField(blank=True, null=True, upload_to='event_edits/')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='events.event')),
                ('new_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.category')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_event_edits', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_edit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на правку события',
                'verbose_name_plural': 'Заявки на правку событий',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('event',), name='uniq_pending_edit_per_event')],
            },
        ),
    ]
