# Generated by Django 5.2.7 on 2025-10-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_seed_initial_taxonomies'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEvent',
            fields=[
            ],
            options={
                'verbose_name': 'Событие на модерации',
                'verbose_name_plural': 'События на модерации',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
    ]
